### ISSUE TITLE
Typing .lyrics will give the lyrics to Downsyde - Undefined

### ISSUE THREAD

**Issue by ghost** [powercord-community/lyrics#3]
I asssume that means the song was not found. Spotify is playing.

**Comment by davidcralph** [comment]
By you mean typing ".lyrics", do you mean without any input afterwards?

**Comment by ghost** [comment]
Yes I do. I realize I should has put this, but I am on the latest version, and am on Windows 10

**Comment by davidcralph** [comment]
Try the latest version I just pushed, it should return an error now if you don't provide any args (and Spotify isn't detected).

I noticed you had Spotify enabled, please check if you have pc-spotify installed and Powercord + Discord connected to your Spotify account.

**Comment by davidcralph** [comment]
Should have been fixed in #5
