### ISSUE TITLE
.lyrics does not send the lyrics to your current Spotify song

### ISSUE THREAD

**Issue by myerDOT** [powercord-community/lyrics#4]
### Expected Behavior
After typing `.lyrics`, it should send the lyrics to my current Spotify song. (and yes, it is being detected, as it shows on the Spotify plugin)
![image](https://user-images.githubusercontent.com/19848162/90099264-09ac8700-dd08-11ea-982d-fe53dadcab4e.png)
### Actual Behavior
The plugin asks for args:
![image](https://user-images.githubusercontent.com/19848162/90099326-2c3ea000-dd08-11ea-8dcf-51a12a7b86ad.png)
### Steps To Reproduce
Do I really need to explain?
### Possibly Relevant Information
![image](https://user-images.githubusercontent.com/19848162/90099397-5abc7b00-dd08-11ea-82ef-0d2c7ee14e56.png)
![image](https://user-images.githubusercontent.com/19848162/90099415-6b6cf100-dd08-11ea-8a76-0bb8e5438fc9.png)

**Comment by davidcralph** [comment]
Should have been fixed in #5
